name: Publish NuGet Package

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Extract tag info
        id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}       # e.g., attack-v0.2.0
          PACKAGE_KEY=$(echo $TAG | cut -d'-' -f1) # attack
          VERSION=$(echo $TAG | cut -d'-' -f2)     # v0.2.0
          VERSION=${VERSION#v}                       # strip leading 'v'
          
          # Map tag key to project name
          case "$PACKAGE_KEY" in
            attack) PROJECT_NAME="Onyx.Attack" ;;
            defense) PROJECT_NAME="Onyx.Defense" ;;
            shared) PROJECT_NAME="Onyx.Shared" ;;
            *) echo "Unknown package key $PACKAGE_KEY"; exit 1 ;;
          esac

          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update csproj version
        run: |
          dotnet msbuild ./src/$PROJECT_NAME/$PROJECT_NAME.csproj \
            /t:UpdateVersion /p:Version=$PACKAGE_VERSION

      - name: Pack NuGet package
        run: |
          dotnet pack ./src/$PROJECT_NAME/$PROJECT_NAME.csproj \
            -c Release -o ./nupkg /p:PackageVersion=$PACKAGE_VERSION

      - name: Push to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
